"""Markdown output generator for news articles."""

from pathlib import Path
from datetime import datetime
from typing import List
from src.models import RankedArticle, Article
from src.filter.date_filter import DateFilter


class MarkdownGenerator:
    """Generates markdown output for ranked articles."""
    
    def __init__(self, output_dir: str = "./Extrablatt"):
        """
        Initialize markdown generator.
        
        Args:
            output_dir: Directory to save markdown files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate(
        self,
        articles: List[RankedArticle],
        date_range: str,
        region: str = "global",
        metadata: dict = None
    ) -> str:
        """
        Generate and save markdown report.
        
        Args:
            articles: List of RankedArticle objects
            date_range: Time range identifier (e.g., '7d', 'today')
            region: Region filter applied
            metadata: Optional metadata dict (sources count, etc.)
            
        Returns:
            Path to generated markdown file
        """
        markdown = self._build_markdown(articles, date_range, region, metadata)
        
        # Generate filename
        timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
        filename = f"news_{date_range}_{timestamp}.md"
        filepath = self.output_dir / filename
        
        # Write file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        return str(filepath)
    
    def _build_markdown(
        self,
        articles: List[RankedArticle],
        date_range: str,
        region: str,
        metadata: dict = None
    ) -> str:
        """
        Build markdown content.
        
        Args:
            articles: List of RankedArticle objects
            date_range: Time range identifier
            region: Region filter applied
            metadata: Optional metadata dict
            
        Returns:
            Markdown string
        """
        lines = []
        
        # Header
        lines.append("# Extrablatt – Top News")
        lines.append("")
        
        # Metadata
        now = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
        range_desc = DateFilter.get_range_description(date_range)
        region_str = region.upper() if region != 'global' else 'Global'
        
        lines.append(f"**Report Generated**: {now}")
        lines.append(f"**Time Range**: {range_desc}")
        
        if metadata:
            sources_count = metadata.get('sources_fetched', 0)
            articles_count = metadata.get('articles_fetched', 0)
            lines.append(f"**Coverage**: {sources_count} sources | {articles_count} articles fetched | {len(articles)} stories selected")
        
        lines.append(f"**Regional Filter**: {region_str}")
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # Articles
        if not articles:
            lines.append("No articles found for the specified criteria.")
        else:
            for idx, ranked_article in enumerate(articles, 1):
                lines.append(self._format_article(ranked_article, idx))
                lines.append("")
                lines.append("---")
                lines.append("")
        
        # Footer
        lines.append("*Generated by Zeitungsjunge News Aggregator*")
        lines.append(f"*Report generated: {now}*")
        
        return "\n".join(lines)
    
    def _format_article(self, ranked_article: RankedArticle, index: int) -> str:
        """
        Format a single article as markdown.
        
        Args:
            ranked_article: RankedArticle object
            index: Article number
            
        Returns:
            Markdown string for the article
        """
        article = ranked_article.article
        score = ranked_article.score
        
        lines = []
        
        # Title with score
        lines.append(f"## {index}. {article.title} — Score: {score:.1f}/10")
        lines.append("")
        
        # Sources
        sources = [article.source_name] + ranked_article.duplicate_sources
        source_count = len(sources)
        sources_str = ", ".join(sources)
        
        lines.append(f"- **Sources**: {sources_str} ({source_count} {'source' if source_count == 1 else 'sources'})")
        
        # Published date
        pub_date = article.published_date.strftime('%Y-%m-%d %H:%M UTC')
        lines.append(f"- **Published**: {pub_date}")
        
        # Description
        if article.description:
            lines.append(f"- **Summary**: {article.description}")
        
        # Link
        lines.append(f"- **Read More**: [{article.url}]({article.url})")
        
        return "\n".join(lines)
