import { format } from 'date-fns';
import { de } from 'date-fns/locale';
import { filterByTopic, getCurrentExtrablattTopic, getAllTopicsMetadata, getAvailableTopics } from './topic-filter.js';

/**
 * Generate Markdown output for articles
 */
export function generateMarkdown(articles, timeRange = 'week', rangeLabel = 'Last 7 Days') {
  const timestamp = format(new Date(), 'PPP p', { locale: de });

  let md = `# Tech & E-Commerce Headlines\n\n`;
  md += `**Generated:** ${timestamp}\n\n`;
  md += `## Report: ${rangeLabel}\n\n`;

  if (articles.length === 0) {
    md += `No articles found for this time range.\n`;
    return md;
  }

  md += `**Total Articles:** ${articles.length}\n\n`;

  // Group by category
  const grouped = groupByCategory(articles);

  for (const [category, items] of Object.entries(grouped)) {
    if (items.length === 0) continue;

    md += `### ${getCategoryEmoji(category)} ${category}\n\n`;

    items.forEach((article, index) => {
      const dateStr = format(new Date(article.publishedAt), 'dd.MM.yyyy', { locale: de });
      const ecomBadge = article.relevanceCategory === 'E-Commerce' ? ' [E-COMMERCE]' : '';
      md += `${index + 1}. **${article.title}**${ecomBadge}\n`;
      md += `   - Source: ${article.source} | Date: ${dateStr}\n`;
      md += `   - Score: ${(article.score * 100).toFixed(1)}%\n`;
       md += `   - [Read More](${article.link})\n`;
      md += `   > ${article.description}\n\n`;
    });
  }

  md += `---\n\n`;
  md += `*Generated by Zeitungsjunge • ${timestamp}*\n`;

  return md;
}

/**
 * Group articles by category
 */
function groupByCategory(articles) {
  const grouped = {
    'AI & Machine Learning': [],
    'Technology': [],
    'E-Commerce': [],
    'PIM & Data Management': [],
    'Agentic & Automation': []
  };

  articles.forEach(article => {
    if (article.relevanceCategory === 'AI') {
      grouped['AI & Machine Learning'].push(article);
    } else if (article.relevanceCategory === 'Tech') {
      grouped['Technology'].push(article);
    } else if (article.relevanceCategory === 'E-Commerce') {
      grouped['E-Commerce'].push(article);
    } else if (article.relevanceCategory === 'PIM/MDM') {
      grouped['PIM & Data Management'].push(article);
    } else if (article.relevanceCategory === 'Agentic') {
      grouped['Agentic & Automation'].push(article);
    }
  });

  return grouped;
}

function getCategoryEmoji(category) {
  const labelMap = {
    'AI & Machine Learning': '[AI]',
    'Technology': '[TECH]',
    'E-Commerce': '[ECOM]',
    'PIM & Data Management': '[PIM]',
    'Agentic & Automation': '[AGENT]'
  };
  return labelMap[category] || '[NEWS]';
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text) {
  if (!text) return '';
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}

/**
 * Generate HTML output with modern design - V2 with expanded content
 */
export function generateHTML(articles, timeRange = 'week', rangeLabel = 'Last 7 Days') {
  const timestamp = format(new Date(), 'PPP p', { locale: de });
  
  // Get extrablatt configuration
  const currentTopic = getCurrentExtrablattTopic();
  const topicsMetadata = getAllTopicsMetadata();
  const topicNames = getAvailableTopics();
  
  // Pre-filter articles for all topics (for dynamic switching)
  const topicArticles = {};
  for (const topic of topicNames) {
    topicArticles[topic] = filterByTopic(articles, topic, 20);
  }
  
  // Get current extrablatt articles
  const extrablattArticles = topicArticles[currentTopic] || [];
  
  // Helper function to generate article card HTML
  const generateArticleCard = (article, topicConfig) => {
    const dateStr = format(new Date(article.publishedAt), 'dd.MM.yyyy', { locale: de });
    const topicBadge = `<span class="extrablatt-topic-badge" style="background-color: ${topicConfig.color}20; color: ${topicConfig.color}; border: 1px solid ${topicConfig.color};">${topicConfig.label}</span>`;
    
    return `
      <div class="article-card extrablatt-card">
        <div class="article-inner">
          <h3 class="article-title">${escapeHtml(article.title)}</h3>
          <div class="article-meta-top">
            <span class="article-source">${article.source}</span>
            <span class="article-date">${dateStr}</span>
            ${topicBadge}
          </div>
          <p class="article-description">${escapeHtml(article.description)}</p>
          <div class="article-footer">
            <div class="article-score">
              ${(article.score * 100).toFixed(1)}% relevance
            </div>
            <a href="${article.link}" target="_blank" rel="noopener noreferrer" class="article-link">Read article</a>
          </div>
        </div>
      </div>
    `;
  };
  
  
  // Prioritize E-Commerce content
  const sorted = articles.sort((a, b) => {
    const aIsEcom = a.relevanceCategory === 'E-Commerce' ? 1 : 0;
    const bIsEcom = b.relevanceCategory === 'E-Commerce' ? 1 : 0;
    if (bIsEcom !== aIsEcom) return bIsEcom - aIsEcom;
    return b.score - a.score;
  });
  
  const grouped = groupByCategory(sorted);

  const labelMap = {
    'AI & Machine Learning': '[AI]',
    'Technology': '[TECH]',
    'E-Commerce': '[ECOM]',
    'PIM & Data Management': '[PIM]',
    'Agentic & Automation': '[AGENT]'
  };

  // Build extrablatt section
  let extrablattHtml = '';
  if (extrablattArticles.length > 0) {
    const topicConfig = topicsMetadata[currentTopic];
    let extrablattArticlesHtml = '';
    
    for (const article of extrablattArticles) {
      extrablattArticlesHtml += generateArticleCard(article, topicConfig);
    }

    // Build topic selector and search controls
    let topicOptions = '';
    for (const topic of topicNames) {
      topicOptions += `<button class="topic-tab" data-topic="${topic}" ${topic === currentTopic ? 'data-active="true"' : ''}>${topicsMetadata[topic].label} ${topic}</button>`;
    }

    extrablattHtml = `
      <div class="extrablatt-section">
        <div class="extrablatt-header">
          <h2>EXTRABLATT: ${currentTopic.toUpperCase()}</h2>
          <p class="extrablatt-subtitle">${topicConfig.description}</p>
        </div>
        
        <div class="extrablatt-controls">
          <div class="topic-selector">
            ${topicOptions}
          </div>
          <div class="search-container">
            <input type="text" id="extrablatt-search" placeholder="Search..." class="search-input">
            <span class="search-results-count">(<span id="results-count">${extrablattArticles.length}</span> articles)</span>
          </div>
        </div>
        
        <div class="articles-grid extrablatt-grid" id="extrablatt-articles">
          ${extrablattArticlesHtml}
        </div>
      </div>
    `;
  }

  const emptyState = articles.length === 0 
    ? '<div class="empty-state">No articles found for this time range.</div>'
    : '';

  const html = `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Zeitungsjunge - Tech & E-Commerce Headlines</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    :root {
      --primary: #00d4ff;
      --secondary: #ff006e;
      --dark: #0a0e27;
      --darker: #050811;
      --light: #f0f9ff;
      --text: #e0e8ff;
      --border: #1e2749;
      --success: #00d084;
      --warning: #ffa500;
      --ecom: #ff9500;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      background: linear-gradient(135deg, var(--darker) 0%, #1a1e35 100%);
      color: var(--text);
      line-height: 1.6;
    }

    .container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px;
    }

    header {
      background: linear-gradient(135deg, rgba(0, 212, 255, 0.1) 0%, rgba(255, 0, 110, 0.1) 100%);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 40px 30px 30px;
      margin-bottom: 40px;
      text-align: center;
      backdrop-filter: blur(10px);
    }

    h1 {
      font-size: 2.5em;
      margin-bottom: 10px;
      background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }

    h1 a {
      background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
      text-decoration: none;
    }

    nav {
      display: flex;
      justify-content: center;
      gap: 8px;
      margin-top: 20px;
      flex-wrap: wrap;
    }

    nav a {
      color: var(--text);
      text-decoration: none;
      padding: 6px 16px;
      border-radius: 20px;
      border: 1px solid var(--border);
      font-size: 0.85em;
      transition: all 0.2s;
      opacity: 0.7;
    }

    nav a:hover {
      border-color: var(--primary);
      color: var(--primary);
      opacity: 1;
    }

    nav a.active {
      background: rgba(0, 212, 255, 0.15);
      border-color: var(--primary);
      color: var(--primary);
      opacity: 1;
      font-weight: 600;
    }

    .subtitle {
      font-size: 1.1em;
      color: var(--text);
      opacity: 0.8;
      margin-bottom: 15px;
    }

    .meta {
      display: flex;
      justify-content: center;
      gap: 20px;
      font-size: 0.9em;
      color: var(--primary);
      flex-wrap: wrap;
    }

    .meta-item {
      display: flex;
      align-items: center;
      gap: 5px;
    }

    .category-section {
      margin-bottom: 50px;
    }

    .category-header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 2px solid var(--border);
    }

    .category-label {
      font-size: 1.1em;
      font-weight: 600;
      background: rgba(0, 212, 255, 0.2);
      padding: 4px 8px;
      border-radius: 4px;
    }

    .category-title {
      font-size: 1.3em;
      font-weight: 600;
    }

    .article-count {
      margin-left: auto;
      background: rgba(0, 212, 255, 0.2);
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 0.85em;
      color: var(--primary);
    }

    .articles-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(380px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }

    .article-card {
      background: linear-gradient(135deg, rgba(30, 39, 73, 0.6) 0%, rgba(20, 25, 50, 0.6) 100%);
      border: 1px solid var(--border);
      border-radius: 12px;
      overflow: hidden;
      transition: all 0.3s ease;
      display: flex;
      flex-direction: column;
      position: relative;
    }

    .article-card.ecom-featured {
      border-color: var(--ecom);
      border-width: 2px;
      background: linear-gradient(135deg, rgba(255, 149, 0, 0.1) 0%, rgba(30, 39, 73, 0.6) 100%);
    }

    .article-card::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      height: 3px;
      background: linear-gradient(90deg, var(--primary), var(--secondary));
      transform: scaleX(0);
      transform-origin: left;
      transition: transform 0.3s ease;
    }

    .article-card.ecom-featured::before {
      background: linear-gradient(90deg, var(--ecom), #ff6b6b);
    }

    .article-card:hover {
      border-color: var(--primary);
      background: linear-gradient(135deg, rgba(0, 212, 255, 0.15) 0%, rgba(255, 0, 110, 0.15) 100%);
      box-shadow: 0 8px 32px rgba(0, 212, 255, 0.1);
    }

    .article-card.ecom-featured:hover {
      border-color: var(--ecom);
      background: linear-gradient(135deg, rgba(255, 149, 0, 0.15) 0%, rgba(30, 39, 73, 0.7) 100%);
      box-shadow: 0 8px 32px rgba(255, 149, 0, 0.2);
    }

    .article-card:hover::before {
      transform: scaleX(1);
    }

    .article-inner {
      padding: 20px;
      display: flex;
      flex-direction: column;
      flex-grow: 1;
    }

    .article-title {
      font-size: 1.15em;
      font-weight: 600;
      margin-bottom: 12px;
      color: var(--light);
      line-height: 1.4;
    }

    .article-meta-top {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 0.8em;
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 1px solid rgba(0, 212, 255, 0.2);
      flex-wrap: wrap;
      gap: 5px;
    }

    .article-source {
      color: var(--primary);
      font-weight: 600;
    }

    .article-date {
      color: var(--text);
      opacity: 0.6;
    }

    .article-score {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      background: rgba(0, 208, 132, 0.15);
      padding: 4px 8px;
      border-radius: 4px;
      color: var(--success);
      font-size: 0.8em;
      font-weight: 600;
    }

    .article-description {
      color: var(--text);
      font-size: 0.95em;
      margin-bottom: 15px;
      opacity: 0.95;
      line-height: 1.5;
      flex-grow: 1;
      max-height: 200px;
      overflow-y: auto;
    }

    .article-footer {
      display: flex;
      gap: 10px;
      margin-top: 15px;
      padding-top: 15px;
      border-top: 1px solid var(--border);
      align-items: center;
      flex-wrap: wrap;
    }

    .article-link {
      flex: 1;
      display: inline-block;
      padding: 10px 15px;
      background: linear-gradient(135deg, var(--primary) 0%, rgba(0, 212, 255, 0.7) 100%);
      color: var(--dark);
      text-decoration: none;
      font-weight: 600;
      border-radius: 6px;
      text-align: center;
      transition: all 0.3s ease;
      font-size: 0.9em;
      min-width: 150px;
    }

    .article-link:hover {
      background: linear-gradient(135deg, var(--secondary) 0%, rgba(255, 0, 110, 0.7) 100%);
      transform: translateY(-2px);
    }

    .article-ecom-badge {
      background: rgba(255, 149, 0, 0.2);
      color: var(--ecom);
      padding: 5px 10px;
      border-radius: 4px;
      font-size: 0.75em;
      font-weight: 700;
      text-transform: uppercase;
      border: 1px solid var(--ecom);
    }

    .extrablatt-section {
      background: linear-gradient(135deg, rgba(0, 212, 255, 0.05) 0%, rgba(255, 0, 110, 0.05) 100%);
      border: 2px solid var(--primary);
      border-radius: 12px;
      padding: 30px;
      margin-bottom: 50px;
    }

    .extrablatt-header {
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 2px solid var(--primary);
    }

    .extrablatt-header h2 {
      font-size: 1.5em;
      font-weight: 700;
      color: var(--primary);
      margin-bottom: 5px;
    }

    .extrablatt-subtitle {
      font-size: 0.95em;
      color: var(--text);
      opacity: 0.8;
    }

    .extrablatt-controls {
      display: flex;
      flex-direction: column;
      gap: 15px;
      margin-bottom: 25px;
    }

    .topic-selector {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
    }

    .topic-tab {
      padding: 8px 15px;
      background: rgba(0, 212, 255, 0.1);
      border: 1px solid var(--border);
      color: var(--text);
      border-radius: 6px;
      cursor: pointer;
      font-size: 0.9em;
      font-weight: 500;
      transition: all 0.3s ease;
    }

    .topic-tab:hover {
      background: rgba(0, 212, 255, 0.2);
      border-color: var(--primary);
    }

    .topic-tab[data-active="true"] {
      background: var(--primary);
      color: var(--dark);
      border-color: var(--primary);
      font-weight: 600;
    }

    .search-container {
      display: flex;
      align-items: center;
      gap: 10px;
    }

    .search-input {
      flex: 1;
      padding: 10px 15px;
      background: rgba(0, 212, 255, 0.1);
      border: 1px solid var(--border);
      color: var(--text);
      border-radius: 6px;
      font-size: 0.9em;
    }

    .search-input::placeholder {
      color: var(--text);
      opacity: 0.5;
    }

    .search-input:focus {
      outline: none;
      border-color: var(--primary);
      background: rgba(0, 212, 255, 0.15);
    }

    .search-results-count {
      font-size: 0.85em;
      color: var(--text);
      opacity: 0.7;
      white-space: nowrap;
    }

    .extrablatt-grid {
      margin-top: 20px;
    }

    .extrablatt-card {
      border-color: var(--primary);
      background: rgba(0, 212, 255, 0.05);
    }

    .extrablatt-topic-badge {
      display: inline-block;
      padding: 5px 10px;
      border-radius: 4px;
      font-size: 0.75em;
      font-weight: 700;
      text-transform: uppercase;
    }

    .empty-state {
      text-align: center;
      padding: 40px;
      color: var(--text);
      opacity: 0.6;
    }

    footer {
      text-align: center;
      padding: 20px;
      border-top: 1px solid var(--border);
      margin-top: 50px;
      color: var(--text);
      opacity: 0.6;
      font-size: 0.9em;
    }

    @media (max-width: 768px) {
      h1 {
        font-size: 1.8em;
      }

      .articles-grid {
        grid-template-columns: 1fr;
      }

      header {
        padding: 20px;
      }

      .meta {
        flex-direction: column;
        gap: 10px;
      }

      .article-description {
        max-height: none;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1><a href="./index.html">Zeitungsjunge</a></h1>
      <p class="subtitle">Smart Headlines for Tech & E-Commerce</p>
      <div class="meta">
        <div class="meta-item">
          <span>Time Range:</span>
          <strong>${rangeLabel}</strong>
        </div>
        <div class="meta-item">
          <span>Articles:</span>
          <strong>${articles.length}</strong>
        </div>
        <div class="meta-item">
          <span>Updated:</span>
          <strong>${timestamp}</strong>
        </div>
      </div>
      <nav>
        <a href="./today.html" ${timeRange === 'today' ? 'class="active"' : ''}>Today</a>
        <a href="./week.html" ${timeRange === 'week' ? 'class="active"' : ''}>This Week</a>
        <a href="./month.html" ${timeRange === 'month' ? 'class="active"' : ''}>This Month</a>
        <a href="./quarter.html" ${timeRange === 'all' ? 'class="active"' : ''}>Last 90 Days</a>
      </nav>
    </header>

    ${emptyState}

    ${extrablattHtml}

     <footer>
       <p>Generated by Zeitungsjunge • ${timestamp}</p>
       <p>Sources: TechCrunch, etailment, The Verge, ArsTechnica, Wired</p>
     </footer>
   </div>

    <script>
      // Initialize extrablatt interactive features
      const allTopicArticles = ${JSON.stringify(topicArticles)};
      const topicsMetadata = ${JSON.stringify(topicsMetadata)};
      const topicNames = ${JSON.stringify(topicNames)};
      
      const searchInput = document.getElementById('extrablatt-search');
      const topicTabs = document.querySelectorAll('.topic-tab');
      const extrablattGrid = document.getElementById('extrablatt-articles');
      const resultsCount = document.getElementById('results-count');

      if (searchInput) {
        searchInput.addEventListener('input', function(e) {
          const query = e.target.value.toLowerCase();
          filterExtrablattArticles(query);
        });
      }

      topicTabs.forEach(tab => {
        tab.addEventListener('click', function(e) {
          e.preventDefault();
          const topic = this.dataset.topic;
          switchTopic(topic);
        });
      });

      function filterExtrablattArticles(query) {
        const cards = extrablattGrid.querySelectorAll('.article-card');
        let visibleCount = 0;

        cards.forEach(card => {
          const title = card.querySelector('.article-title').textContent.toLowerCase();
          const description = card.querySelector('.article-description').textContent.toLowerCase();
          const source = card.querySelector('.article-source').textContent.toLowerCase();

          const matches = title.includes(query) || description.includes(query) || source.includes(query);
          card.style.display = matches ? '' : 'none';
          if (matches) visibleCount++;
        });

        resultsCount.textContent = visibleCount;
      }

      function switchTopic(topic) {
        // Get articles for this topic
        const articles = allTopicArticles[topic] || [];
        if (articles.length === 0) {
          alert('No articles found for ' + topic);
          return;
        }

        const topicConfig = topicsMetadata[topic];
        
        // Update active tab
        topicTabs.forEach(tab => tab.removeAttribute('data-active'));
        document.querySelector('[data-topic="' + topic + '"]').setAttribute('data-active', 'true');

        // Update header
        document.querySelector('.extrablatt-header h2').textContent = 'EXTRABLATT: ' + topic.toUpperCase();
        document.querySelector('.extrablatt-subtitle').textContent = topicConfig.description;

        // Update search placeholder
        if (searchInput) {
          searchInput.placeholder = 'Search ' + topic + '...';
          searchInput.value = '';
        }

        // Render articles
        let articlesHtml = '';
        articles.forEach(article => {
          const dateStr = new Date(article.publishedAt).toLocaleDateString('de-DE');
          const topicBadge = '<span class="extrablatt-topic-badge" style="background-color: ' + topicConfig.color + '20; color: ' + topicConfig.color + '; border: 1px solid ' + topicConfig.color + ';">' + topicConfig.label + '</span>';
          
          articlesHtml += '<div class="article-card extrablatt-card">' +
            '<div class="article-inner">' +
            '<h3 class="article-title">' + escapeHtml(article.title) + '</h3>' +
            '<div class="article-meta-top">' +
            '<span class="article-source">' + article.source + '</span>' +
            '<span class="article-date">' + dateStr + '</span>' +
            topicBadge +
            '</div>' +
            '<p class="article-description">' + escapeHtml(article.description) + '</p>' +
            '<div class="article-footer">' +
            '<div class="article-score">' + (article.score * 100).toFixed(1) + '% relevance</div>' +
            '<a href="' + article.link + '" target="_blank" rel="noopener noreferrer" class="article-link">Read article</a>' +
            '</div>' +
            '</div>' +
            '</div>';
        });

        extrablattGrid.innerHTML = articlesHtml;
        resultsCount.textContent = articles.length;
      }

      function escapeHtml(text) {
        if (!text) return '';
        const map = {
          '&': '&amp;',
          '<': '&lt;',
          '>': '&gt;',
          '"': '&quot;',
          "'": '&#039;'
        };
        return text.replace(/[&<>"']/g, m => map[m]);
      }
    </script>
 </body>
 </html>`;

  return html;
}
