import { format } from 'date-fns';
import { de } from 'date-fns/locale';

/**
 * Generate Markdown output for articles
 */
export function generateMarkdown(articles, timeRange = 'week', rangeLabel = 'Last 7 Days') {
  const timestamp = format(new Date(), 'PPP p', { locale: de });

  let md = `# Tech & E-Commerce Headlines\n\n`;
  md += `**Generated:** ${timestamp}\n\n`;
  md += `## Report: ${rangeLabel}\n\n`;

  if (articles.length === 0) {
    md += `No articles found for this time range.\n`;
    return md;
  }

  md += `**Total Articles:** ${articles.length}\n\n`;

  // Group by category
  const grouped = groupByCategory(articles);

  for (const [category, items] of Object.entries(grouped)) {
    if (items.length === 0) continue;

    md += `### ${getCategoryEmoji(category)} ${category}\n\n`;

    items.forEach((article, index) => {
      const dateStr = format(new Date(article.publishedAt), 'dd.MM.yyyy', { locale: de });
      const ecomBadge = article.relevanceCategory === 'E-Commerce' ? ' [E-COMMERCE]' : '';
      md += `${index + 1}. **${article.title}**${ecomBadge}\n`;
      md += `   - Source: ${article.source} | Date: ${dateStr}\n`;
      md += `   - Score: ${(article.score * 100).toFixed(1)}%\n`;
       md += `   - [Read More](${article.link})\n`;
      md += `   > ${article.description}\n\n`;
    });
  }

  md += `---\n\n`;
  md += `*Generated by Zeitungsjunge • ${timestamp}*\n`;

  return md;
}

/**
 * Group articles by category
 */
function groupByCategory(articles) {
  const grouped = {
    'AI & Machine Learning': [],
    'Technology': [],
    'E-Commerce': [],
    'PIM & Data Management': [],
    'Agentic & Automation': []
  };

  articles.forEach(article => {
    if (article.relevanceCategory === 'AI') {
      grouped['AI & Machine Learning'].push(article);
    } else if (article.relevanceCategory === 'Tech') {
      grouped['Technology'].push(article);
    } else if (article.relevanceCategory === 'E-Commerce') {
      grouped['E-Commerce'].push(article);
    } else if (article.relevanceCategory === 'PIM/MDM') {
      grouped['PIM & Data Management'].push(article);
    } else if (article.relevanceCategory === 'Agentic') {
      grouped['Agentic & Automation'].push(article);
    }
  });

  return grouped;
}

function getCategoryEmoji(category) {
  const labelMap = {
    'AI & Machine Learning': '[AI]',
    'Technology': '[TECH]',
    'E-Commerce': '[ECOM]',
    'PIM & Data Management': '[PIM]',
    'Agentic & Automation': '[AGENT]'
  };
  return labelMap[category] || '[NEWS]';
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text) {
  if (!text) return '';
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}

/**
 * Generate HTML output with modern design - V2 with expanded content
 */
export function generateHTML(articles, timeRange = 'week', rangeLabel = 'Last 7 Days') {
  const timestamp = format(new Date(), 'PPP p', { locale: de });
  
  // Prioritize E-Commerce content
  const sorted = articles.sort((a, b) => {
    const aIsEcom = a.relevanceCategory === 'E-Commerce' ? 1 : 0;
    const bIsEcom = b.relevanceCategory === 'E-Commerce' ? 1 : 0;
    if (bIsEcom !== aIsEcom) return bIsEcom - aIsEcom;
    return b.score - a.score;
  });
  
  const grouped = groupByCategory(sorted);

  const labelMap = {
    'AI & Machine Learning': '[AI]',
    'Technology': '[TECH]',
    'E-Commerce': '[ECOM]',
    'PIM & Data Management': '[PIM]',
    'Agentic & Automation': '[AGENT]'
  };

  // Build category sections
  let categorySections = '';
  for (const [category, items] of Object.entries(grouped)) {
    if (items.length === 0) continue;

    let articlesHtml = '';
    for (const article of items) {
      const isEcom = article.relevanceCategory === 'E-Commerce';
      const ecomClass = isEcom ? 'ecom-featured' : '';
       const ecomBadge = isEcom ? '<span class="article-ecom-badge">[ECOM]</span>' : '';
      const dateStr = format(new Date(article.publishedAt), 'dd.MM.yyyy', { locale: de });

      articlesHtml += `
              <div class="article-card ${ecomClass}">
                <div class="article-inner">
                  <h3 class="article-title">${escapeHtml(article.title)}</h3>
                  <div class="article-meta-top">
                    <span class="article-source">${article.source}</span>
                    <span class="article-date">${dateStr}</span>
                    ${ecomBadge}
                  </div>
                  <p class="article-description">${escapeHtml(article.description)}</p>
                  <div class="article-footer">
                    <div class="article-score">
                      ${(article.score * 100).toFixed(1)}% relevance
                    </div>
                    <a href="${article.link}" target="_blank" rel="noopener noreferrer" class="article-link">Read article</a>
                  </div>
                </div>
              </div>
            `;
    }

    categorySections += `
        <div class="category-section">
          <div class="category-header">
            <span class="category-label">${labelMap[category]}</span>
            <h2 class="category-title">${category}</h2>
            <div class="article-count">${items.length} Artikel</div>
          </div>
          <div class="articles-grid">
            ${articlesHtml}
          </div>
        </div>
      `;
  }

  const emptyState = articles.length === 0 
    ? '<div class="empty-state">Keine Artikel für diesen Zeitraum gefunden.</div>'
    : '';

  const html = `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Zeitungsjunge - Tech & E-Commerce Headlines</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    :root {
      --primary: #00d4ff;
      --secondary: #ff006e;
      --dark: #0a0e27;
      --darker: #050811;
      --light: #f0f9ff;
      --text: #e0e8ff;
      --border: #1e2749;
      --success: #00d084;
      --warning: #ffa500;
      --ecom: #ff9500;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      background: linear-gradient(135deg, var(--darker) 0%, #1a1e35 100%);
      color: var(--text);
      line-height: 1.6;
    }

    .container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px;
    }

    header {
      background: linear-gradient(135deg, rgba(0, 212, 255, 0.1) 0%, rgba(255, 0, 110, 0.1) 100%);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 40px 30px;
      margin-bottom: 40px;
      text-align: center;
      backdrop-filter: blur(10px);
    }

    h1 {
      font-size: 2.5em;
      margin-bottom: 10px;
      background: linear-gradient(135deg, var(--primary) 0%, var(--secondary) 100%);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      background-clip: text;
    }

    .subtitle {
      font-size: 1.1em;
      color: var(--text);
      opacity: 0.8;
      margin-bottom: 15px;
    }

    .meta {
      display: flex;
      justify-content: center;
      gap: 20px;
      font-size: 0.9em;
      color: var(--primary);
      flex-wrap: wrap;
    }

    .meta-item {
      display: flex;
      align-items: center;
      gap: 5px;
    }

    .category-section {
      margin-bottom: 50px;
    }

    .category-header {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 20px;
      padding-bottom: 15px;
      border-bottom: 2px solid var(--border);
    }

    .category-label {
      font-size: 1.1em;
      font-weight: 600;
      background: rgba(0, 212, 255, 0.2);
      padding: 4px 8px;
      border-radius: 4px;
    }

    .category-title {
      font-size: 1.3em;
      font-weight: 600;
    }

    .article-count {
      margin-left: auto;
      background: rgba(0, 212, 255, 0.2);
      padding: 4px 12px;
      border-radius: 20px;
      font-size: 0.85em;
      color: var(--primary);
    }

    .articles-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(380px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }

    .article-card {
      background: linear-gradient(135deg, rgba(30, 39, 73, 0.6) 0%, rgba(20, 25, 50, 0.6) 100%);
      border: 1px solid var(--border);
      border-radius: 12px;
      overflow: hidden;
      transition: all 0.3s ease;
      display: flex;
      flex-direction: column;
      position: relative;
    }

    .article-card.ecom-featured {
      border-color: var(--ecom);
      border-width: 2px;
      background: linear-gradient(135deg, rgba(255, 149, 0, 0.1) 0%, rgba(30, 39, 73, 0.6) 100%);
    }

    .article-card::before {
      content: '';
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      height: 3px;
      background: linear-gradient(90deg, var(--primary), var(--secondary));
      transform: scaleX(0);
      transform-origin: left;
      transition: transform 0.3s ease;
    }

    .article-card.ecom-featured::before {
      background: linear-gradient(90deg, var(--ecom), #ff6b6b);
    }

    .article-card:hover {
      border-color: var(--primary);
      background: linear-gradient(135deg, rgba(0, 212, 255, 0.15) 0%, rgba(255, 0, 110, 0.15) 100%);
      box-shadow: 0 8px 32px rgba(0, 212, 255, 0.1);
    }

    .article-card.ecom-featured:hover {
      border-color: var(--ecom);
      background: linear-gradient(135deg, rgba(255, 149, 0, 0.15) 0%, rgba(30, 39, 73, 0.7) 100%);
      box-shadow: 0 8px 32px rgba(255, 149, 0, 0.2);
    }

    .article-card:hover::before {
      transform: scaleX(1);
    }

    .article-inner {
      padding: 20px;
      display: flex;
      flex-direction: column;
      flex-grow: 1;
    }

    .article-title {
      font-size: 1.15em;
      font-weight: 600;
      margin-bottom: 12px;
      color: var(--light);
      line-height: 1.4;
    }

    .article-meta-top {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 0.8em;
      margin-bottom: 15px;
      padding-bottom: 10px;
      border-bottom: 1px solid rgba(0, 212, 255, 0.2);
      flex-wrap: wrap;
      gap: 5px;
    }

    .article-source {
      color: var(--primary);
      font-weight: 600;
    }

    .article-date {
      color: var(--text);
      opacity: 0.6;
    }

    .article-score {
      display: inline-flex;
      align-items: center;
      gap: 4px;
      background: rgba(0, 208, 132, 0.15);
      padding: 4px 8px;
      border-radius: 4px;
      color: var(--success);
      font-size: 0.8em;
      font-weight: 600;
    }

    .article-description {
      color: var(--text);
      font-size: 0.95em;
      margin-bottom: 15px;
      opacity: 0.95;
      line-height: 1.5;
      flex-grow: 1;
      max-height: 200px;
      overflow-y: auto;
    }

    .article-footer {
      display: flex;
      gap: 10px;
      margin-top: 15px;
      padding-top: 15px;
      border-top: 1px solid var(--border);
      align-items: center;
      flex-wrap: wrap;
    }

    .article-link {
      flex: 1;
      display: inline-block;
      padding: 10px 15px;
      background: linear-gradient(135deg, var(--primary) 0%, rgba(0, 212, 255, 0.7) 100%);
      color: var(--dark);
      text-decoration: none;
      font-weight: 600;
      border-radius: 6px;
      text-align: center;
      transition: all 0.3s ease;
      font-size: 0.9em;
      min-width: 150px;
    }

    .article-link:hover {
      background: linear-gradient(135deg, var(--secondary) 0%, rgba(255, 0, 110, 0.7) 100%);
      transform: translateY(-2px);
    }

    .article-ecom-badge {
      background: rgba(255, 149, 0, 0.2);
      color: var(--ecom);
      padding: 5px 10px;
      border-radius: 4px;
      font-size: 0.75em;
      font-weight: 700;
      text-transform: uppercase;
      border: 1px solid var(--ecom);
    }

    .empty-state {
      text-align: center;
      padding: 40px;
      color: var(--text);
      opacity: 0.6;
    }

    footer {
      text-align: center;
      padding: 20px;
      border-top: 1px solid var(--border);
      margin-top: 50px;
      color: var(--text);
      opacity: 0.6;
      font-size: 0.9em;
    }

    @media (max-width: 768px) {
      h1 {
        font-size: 1.8em;
      }

      .articles-grid {
        grid-template-columns: 1fr;
      }

      header {
        padding: 20px;
      }

      .meta {
        flex-direction: column;
        gap: 10px;
      }

      .article-description {
        max-height: none;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>Zeitungsjunge</h1>
      <p class="subtitle">Smart Headlines for Tech & E-Commerce</p>
      <div class="meta">
        <div class="meta-item">
          <span>Time Range:</span>
          <strong>${rangeLabel}</strong>
        </div>
        <div class="meta-item">
          <span>Articles:</span>
          <strong>${articles.length}</strong>
        </div>
        <div class="meta-item">
          <span>Updated:</span>
          <strong>${timestamp}</strong>
        </div>
      </div>
    </header>

    ${emptyState}

    ${categorySections}

    <footer>
      <p>Generated by Zeitungsjunge • ${timestamp}</p>
      <p>Sources: TechCrunch, etailment, The Verge, ArsTechnica, Wired</p>
    </footer>
  </div>
</body>
</html>`;

  return html;
}
